"""test2

Revision ID: 9de3fec8a54f
Revises: fca082357a82
Create Date: 2021-06-14 17:44:19.905606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9de3fec8a54f'
down_revision = 'fca082357a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('github_link', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('jobtitle', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('linkedin_link', sa.Text(), nullable=True))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'linkedin_link')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'jobtitle')
    op.drop_column('users', 'github_link')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'about_text')
    # ### end Alembic commands ###
