"""updateproject

Revision ID: c4f400e7a040
Revises: 9de3fec8a54f
Create Date: 2021-06-28 16:57:26.870561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f400e7a040'
down_revision = '9de3fec8a54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'bulletpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'bulletpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
